# Numpy

_Materiale estrapolato dal corso di Machine Learning dell'Università di Bologna tenuto dal prof. Maltoni Davide e dall'assistente Lorenzo Pellegrini_

Numpy è una libreria del linguaggio Python che permette di definire e manipolare vettori e matrici multidimensionali.

Per via della sua facilità d'uso e del gran numero di operazioni messe a disposizione out-of-the-box, Numpy è diventato un punto di riferimento per qualsiasi applicazione di tipo scientifico. Questa libreria nasce con l'intento di sopperire alle mancanze delle strutture dati messe a disposizione nativamente da Python che risultano poco adatte ad applicazioni matematiche.

Di seguito vengono esposte le principali funzionalità messe a disposizione da Numpy. Per una lista completa si rimanda alla [documentazione ufficiale](https://numpy.org/doc/stable/reference/index.html).

In [1]:
import numpy as np

## Array

Al contrario delle liste di Python, gli array di Numpy (**ndarray** - *n-dimensional array*) sono omogenei, cioè possono contenere solamente elementi dello stesso tipo. Inoltre le operazioni aritmetiche e di manipolazione messe a disposizione risultano essere particolarmente ottimizzate.

L'inizializzazione di un **ndarray** è affidata alla funzione **array(...)**. Nella sua versione base la funzione accetta come parametro una lista di valori.

In [2]:
# Definisce un vettore contenente gli elementi da 0 a 5
vector = np.array([0, 1, 2, 3, 4, 5])
print(type(vector))
print('Contenuto di vector:', vector)

<class 'numpy.ndarray'>
Contenuto di vector: [0 1 2 3 4 5]


Si noti che in Numpy un array monodimensionale viene rappresentato come vettore riga (mentre solitamente in matematica quando si parla di vettori ci si riferisce a vettori colonna).

È possibile accedere ai singoli elementi nel seguente modo:

In [3]:
# Accesso in lettura
print(vector[0])

# Accesso in scrittura
vector[2] = 5
print(vector)

vector = np.array([0, 1, 2, 3, 4, 5]) # Ripristina i valori originali

0
[0 1 5 3 4 5]


Numpy è in grado di gestire ndarray multidimensionali.

Di seguito un esempio di dichiarazione di un ndarray bi-dimensionale, cioè una matrice. È possibile dichiarare una matrice utilizzando la funzione array(...). In questo caso il parametro consiste in una lista di liste: ogni sottolista descrive il contenuto di una riga. Le liste devono essere di lunghezza identica.

In [4]:
# Dichiarazione di una matrix 2x3
matrix = np.array([[0,1,2], [3,4,5]])
print('Contenuto della matrice:\n', matrix)

# Accesso agli elementi di una matrice
print(matrix[1][2])
# Sintassi equivalente
print(matrix[1, 2])

Contenuto della matrice:
 [[0 1 2]
 [3 4 5]]
5
5


Numpy mette a disposizione diverse funzioni per la creazione degli array:

In [5]:
# Dichiarazione di una matrice 2x2 inizializzata con tutti gli elementi a 0 
a = np.zeros((2,2))   
print('Zeros:\n', a)
print() 
        
# Dichiarazione di una matrice 1x2 inizializzata con tutti gli elementi a 1 
b = np.ones((1,2))    
print('Ones:\n', b)
print() 

# Dichiarazione di una matrice 2x2 inizializzata con tutti gli elementi a un valore costante 
c = np.full((2,2), 7)  
print('Full:\n', c)
print() 

# Dichiarazione di una matrice identità 3x3
d = np.eye(3)
print('Eye:\n', d)
print() 

# Dichiarazione di una matrice 4x3 contenete valori casuali
e = np.random.random((4,3))
print('Random:\n', e)

Zeros:
 [[0. 0.]
 [0. 0.]]

Ones:
 [[1. 1.]]

Full:
 [[7 7]
 [7 7]]

Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random:
 [[0.64746421 0.06399527 0.64672076]
 [0.38156253 0.43585627 0.72045728]
 [0.67056126 0.53363619 0.79598582]
 [0.25637412 0.5029666  0.61353584]]


## Shape
Si definisce **rank** il numero di dimensioni di un array e **shape** una tupla di interi che esprimono la lunghezza di ciascuna dimensione.

Per comprendere meglio questo concetto si consideri la variabile *vector*: si tratta di un vettore di *rank* 1 e *shape* (6,) (cioè una tupla contenente un solo elemento).

Per ottenere la *shape* di un **ndarray** è sufficiente accederne al relativo attributo, come mostrato nella cella seguente:

In [6]:
print('Rank di vector:', len(vector.shape))
print('Shape di vector :', vector.shape)

print('Rank di matrix:', len(matrix.shape))
print('Shape di matrix :', matrix.shape)

Rank di vector: 1
Shape di vector : (6,)
Rank di matrix: 2
Shape di matrix : (2, 3)


## Reshape
Un **ndarray** può essere manipolato in maniera tale da poter creare un array con *shape* differente a partire dal contenuto iniziale.

Nell'esempio che segue *vector* è trasformato nell'equivalente vettore colonna utilizzando la funzione **reshape(...)**.

In [7]:
# Trasformazione in vettore colonna
column_vector = vector.reshape((6, 1))

print('Contenuto di column_vector:\n', column_vector)

# Nota: l'array originale non è stato modificato
print('vector originale:', vector)

Contenuto di column_vector:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
vector originale: [0 1 2 3 4 5]


Il parametro della funzione **reshape(...)** deve essere una tupla che descrive la *shape* dell'array di output. In questo caso si vuole che gli stessi dati contenuti in *row_vector* vengano utilizzati per creare una matrice di 6 righe e 1 colonna. Il risultato si riflette nell'attributo shape del vettore ottenuto:

In [8]:
print('Rank vettore colonna:', len(column_vector.shape))
print('Shape vettore colonna:', column_vector.shape)

Rank vettore colonna: 2
Shape vettore colonna: (6, 1)


A partire dal vettore colonna è possibile riottenere il relativo vettore riga utilizzando nuovamente utilizzando la funzione **reshape(...)**.

In [9]:
row_vector = column_vector.reshape((1, 6))

print('Contenuto di row_vector:\n', row_vector)
print('Rank di row_vector:', len(row_vector.shape))
print('Shape di row_vector:', row_vector.shape)

Contenuto di row_vector:
 [[0 1 2 3 4 5]]
Rank di row_vector: 2
Shape di row_vector: (1, 6)


Nota: il *row_vector* così ottenuto non è identico al *vector* originale. Si noti come **print(...)** restituisca *\[\[0 1 2 3 4 5\]\]* per *row_vector* e *\[0 1 2 3 4 5\]* per *vector*.

Questo è dovuto al fatto che *row_vector* ha dimensioni *(1, 6)* mentre *vector* ha dimensioni *(6,)*. In altre parole *row_vector* è una matrice 1x6 mentre *vector* è un array monodimensionale (o vettore riga).

La seguente operazione restituirà esattamente il vettore originale. 

In [10]:
print(column_vector.reshape( (6,) ))

# Per array monodimensionali è possibile passare a reshape(...) un singolo valore
print(column_vector.reshape(  6  ))

[0 1 2 3 4 5]
[0 1 2 3 4 5]


## Tipi di dati

Gli array di Numpy sono una griglia di elementi dello stesso tipo. Il tipo di dato degli elementi viene automaticamente inferito da Numpy oppure può essere specificato nella funzione di inizializzazione come parametro opzionale:

In [11]:
x = np.array([1, 2]) # Numpy sceglie il tipo di dati
print(x.dtype)

x = np.array([1.0, 2.0]) # Numpy sceglie il tipo di dati
print(x.dtype)

x = np.array([1, 2], dtype=np.int64) # Forza un tipo di dati                    
print(x.dtype)

int64
float64
int64


## Slicing

Lo *slicing* si applica anche agli **ndarray** ma, a differenza di quanto avviene per le liste, è possibile applicarlo a ogni dimensione dell'array.

P.S. Lo slicing consiste nel suddividere un oggetto in unità numerate secondo un ordine sequenziale. Può trattarsi sia di una lista che dei caratteri di una stringa.

In [12]:
# Crea un ndarray bi-dimensionale di shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()

# Slicing per ottenere una sotto-matrice formata dagli elementi
# delle prime 2 righe in corrispondenza delle colonne 1 e 2
b = a[:2, 1:3]
print(b)
print()

# Uno slice crea una vista, non una copia dei dati
# Modificare uno slice equivale a modificare l'ndarray originale
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]

2
77


## Operazioni algebriche tra vettori
Numpy mette a disposizione le più comuni operazioni algebriche attraverso gli operatori visti per le variabili numeriche (+, -, *, /):

In [13]:
# Reminder: vector = [0, 1, 2, 3, 4, 5]

# Moltiplicazione di un vettore per uno scalare
vector_scalar_prod = vector * 5

# Divisione di un vettore per uno scalare
vector_scalar_div = vector / 5

print('Prodotto per uno scalare:\n', vector_scalar_prod)
print('Divisione per uno scalare:\n', vector_scalar_div)

Prodotto per uno scalare:
 [ 0  5 10 15 20 25]
Divisione per uno scalare:
 [0.  0.2 0.4 0.6 0.8 1. ]


In [14]:
vect1 = np.array([1,2,6])
vect2 = np.array([5,2,3])

# Somma tra vettori
vector_sum = vect1 + vect2

# Sottrazione tra vettori
vector_sub = vect1 - vect2

print('Somma:\n', vector_sum)
print('Sottrazione:\n', vector_sub)

Somma:
 [6 4 9]
Sottrazione:
 [-4  0  3]


Nota: l'operatore *'+'*, quando applicato a due liste "native" di Python, esegue una concatenazione. Tuttavia se lo stesso operatore viene applicato a due **ndarray** quella che si ottiene è una somma algebrica.

## Operazioni algebriche tra matrici
Come già accennato, le matrici possono essere rappresentate tramite **ndarray** di *rank* 2. Numpy mette a disposizione diverse funzioni frequentemente utilizzate nel calcolo matriciale quali: calcolo della trasposta, dell'inversa, del determinante, del prodotto tra matrici, ecc.

### Calcolo della trasposta
È possibile calcolare la trasposta di una matrice richiamando il metodo **.transpose(...)**, oppure utilizzando l'attributo **.T**. In alternativa è anche disponibile la relativa funzione di libreria **np.transpose(...)**.

In [16]:
matrix = np.array([[0,1,2], [3,4,5]])
print('Matrix:\n', matrix)

# Calcolo della trasposta
matrix_transp = matrix.transpose()
print('\nTrasposta di matrix:\n', matrix_transp)
print()

# In maniera equivalente
matrix_transp_T = matrix.T
matrix_transp_np = np.transpose(matrix)

print(matrix_transp_T)
print()
print(matrix_transp_np)

Matrix:
 [[0 1 2]
 [3 4 5]]

Trasposta di matrix:
 [[0 3]
 [1 4]
 [2 5]]

[[0 3]
 [1 4]
 [2 5]]

[[0 3]
 [1 4]
 [2 5]]


### Calcolo dell'inversa
È possibile calcolare l'inversa di una matrice utilizzando la funzione di libreria **np.linalg.inv(...)**.

In [17]:
# Definizione di una matrice quadrata
matrix2 = np.array([[12,-1,0],
                    [7,6,-5],
                    [1,6,9]])

# Calcolo dell'inversa
matrix2_inv = np.linalg.inv(matrix2)           
print('Inversa matrix2:\n', matrix2_inv)

Inversa matrix2:
 [[ 0.07806691  0.00836431  0.00464684]
 [-0.06319703  0.10037175  0.05576208]
 [ 0.03345725 -0.06784387  0.07342007]]


### Calcolo del determinante
È possibile calcolare il determinante di una matrice utilizzando la funzione di libreria **np.linalg.det(...)**.

In [18]:
# Calcolo del determinante
matrix2_det = np.linalg.det(matrix2)
print('Determinante matrix2:', matrix2_det)

Determinante matrix2: 1076.0000000000002


### Somma e sottrazione tra matrici
Esattamente come visto per i vettori, la somma tra matrici è delegata all'operatore "**+**".

In [19]:
# Reminder: matrix = np.array([[0,1,2], [3,4,5]])
print('matrix:\n', matrix)
print()

# Somma e sottrazione (elemento per elemento) di due matrici
matrix3 = np.array([[5,2,6],
                    [8,12,1]])
print('matrix3:\n', matrix3)
print()

matrix_sum = matrix + matrix3
print('Somma:\n', matrix_sum)
print()

matrix_sub = matrix - matrix3
print('Sottrazione:\n', matrix_sub)

matrix:
 [[0 1 2]
 [3 4 5]]

matrix3:
 [[ 5  2  6]
 [ 8 12  1]]

Somma:
 [[ 5  3  8]
 [11 16  6]]

Sottrazione:
 [[-5 -1 -4]
 [-5 -8  4]]


### Moltiplicazione matriciale
La moltiplicazione matriciale è affidata al metodo **.dot(...)**. Questo metodo deve essere richiamato sulla matrice sinistra passando come parametro la matrice destra. In alternativa è possibile utilizzare la funzione di libreria **np.dot(...)** oppure l'operatore **@**.

In [21]:
# Reminder: matrix = [[0,1,2], 
#                      [3,4,5]]
#
#           matrix2 = [[12,-1,0],
#                      [7,6,-5],
#                      [1,6,9]]
print('matrix:\n', matrix)

print('\nmatrix2:\n', matrix2)

# Moltiplicazione matriciale tra le matrici "matrix1" e "matrix2"
mul1 = matrix.dot(matrix2)
print('\nMoltiplicazione tra matrici:\n', mul1)
print()

# In maniera equivalente
mul2_dot = np.dot(matrix, matrix2)
mul2_at = matrix @ matrix2
print(mul2_dot)
print()
print(mul2_at)

matrix:
 [[0 1 2]
 [3 4 5]]

matrix2:
 [[12 -1  0]
 [ 7  6 -5]
 [ 1  6  9]]

Moltiplicazione tra matrici:
 [[ 9 18 13]
 [69 51 25]]

[[ 9 18 13]
 [69 51 25]]

[[ 9 18 13]
 [69 51 25]]


### Prodotto scalare
Utilizzando il metodo **.dot(...)** tra un vettore riga e un vettore colonna è possibile calcolare il loro prodotto scalare.

In [22]:
# Prodotto scalare di due vettori (riga*colonna)
row_vector = column_vector.reshape((1, 6))

mul2 = row_vector.dot(column_vector)
print('mul2:', mul2)

mul2: [[55]]


Attenzione perchè Numpy non restituisce un valore scalare ma una matrice di dimensione 1x1.

In [23]:
print(mul2.shape)

(1, 1)


## Media e deviazione standard di un vettore
È possibile calcolare media e deviazione standard utilizzando i metodi **.mean(...)** e **.std(...)**.

In [24]:
print('row_vector:', row_vector)
print('Media:', row_vector.mean())
print('Deviazione standard:', row_vector.std()) 

row_vector: [[0 1 2 3 4 5]]
Media: 2.5
Deviazione standard: 1.707825127659933


## Trasformazione in scalare
È possibile trasformare un **ndarray** 1x1 in uno scalare.

In [25]:
# sc = np.asscalar(mul2)  # Deprecato
sc = mul2.item()
print('Scalare:', sc)

Scalare: 55


## Prodotto di vettori
Il prodotto tra vettori è gestito in maniera diversa a seconda della *shape* dei vettori coinvolti. Se entrambi i vettori hanno rango 2, è possibile usare indistintamente **.dot(...)**, **\*** o **\@** per eseguire la loro moltiplicazione algebrica. È possibile ottenere lo stesso risultato anche se il vettore di destra (riga) è di rango 1 (il vettore di sinistra deve comunque essere di rango 2): in questo caso è necessario utilizzare l'operatore **\*** mentre gli operatori **.dot(...)** e **\@** restituiranno un errore.

In [26]:
rank_one_vector = np.array([0, 1, 2, 3, 4, 5])
print('column_vector shape:', column_vector.shape)
print('row_vector shape:', row_vector.shape)
print('rank_one_vector shape:', rank_one_vector.shape)
print()

# Moltiplicazione algebrica tra vettori: entrambi i vettori di rango 2
mul3dot = column_vector.dot(row_vector)
mul3at = column_vector @ row_vector # <-- In alternativa
mul3asterisk = column_vector * row_vector # <-- In alternativa
print('mul3dot:\n', mul3dot)
print()
print('mul3at:\n', mul3at)
print()
print('mul3asterisk:\n', mul3asterisk)
print()

# Moltiplicazione algebrica tra vettori: vettore di destra di rango 1
mul4 = column_vector * rank_one_vector
# mul4 = column_vector @ rank_one_vector # <-- Errore!
# mul4 = column_vector.dot(rank_one_vector) # <-- Errore!
print('mul4:\n', mul4)

column_vector shape: (6, 1)
row_vector shape: (1, 6)
rank_one_vector shape: (6,)

mul3dot:
 [[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]

mul3at:
 [[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]

mul3asterisk:
 [[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]

mul4:
 [[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]


Si deve prestare particolare attenzione nel caso in cui entrambi i vettori siano di rango 1: 
- applicando l'operatore **\@** si otterrà il prodotto scalare (senza la necessità di utilizzare **.asscalar()**);
- utilizzando l'operatore **\*** si otterrà un nuovo vettore ottenuto moltiplicando elemento per elemento i vettori originali.

In [27]:
# Prodotto scalare (senza usare .asscalar())
mul5 = rank_one_vector @ rank_one_vector
print('mul5:', mul5)

# Moltiplicazione elemento per elemento
mul6 = rank_one_vector * rank_one_vector
print('mul6:', mul6)

mul5: 55
mul6: [ 0  1  4  9 16 25]


## Somma degli elementi
La somma degli elementi è affidata al metodo **.sum(...)** o alla funzione di libreria **np.sum(...)**.

In [28]:
# Somma degli elementi di un vettore
print(row_vector)
print('Somma:', row_vector.sum())
print()

# Reminder: matrix3 = [[5,2,6],
#                      [8,12,1]]
print('matrix3:\n', matrix3)
print()

# Somma degli elementi di una matrice
elements_sum = matrix3.sum()
print('Somma:', elements_sum)

# Somma degli elementi di una matrice per riga
elements_row_sum = matrix3.sum(axis=1)
print('Somma per riga:', elements_row_sum)

# Somma degli elementi di una matrice per colonna
elements_column_sum = matrix3.sum(axis=0)
print('Somma per colonna:', elements_column_sum)

[[0 1 2 3 4 5]]
Somma: 15

matrix3:
 [[ 5  2  6]
 [ 8 12  1]]

Somma: 34
Somma per riga: [13 21]
Somma per colonna: [13 14  7]


## Minimi e massimi di una matrice
Allo stesso modo è possibile ottenere i minimi e i massimi per riga o colonna utilizzando i metodi **.min(...)** e **.max(...)**. Anche per queste sono disponibili le funzioni di libreria **np.min(...)** e **np.max(...)**.

In [29]:
row_vector2 = np.array([0, 1, 2, 3, 4, 5])
print('row_vector2:', row_vector2)

print('Minimo:', row_vector2.min())
print('Massimo:', row_vector2.max())
print()

# Reminder: matrix3 = [[5,2,6],
#                      [8,12,1]]
print('matrix3:\n', matrix3)

# Minimi delle righe di una matrice
mins = matrix3.min(axis=1)
print('Minimi delle righe:', mins)

# Massimi delle colonne di una matrice
maxs = matrix3.max(axis=0)
print('Massimi delle colonne:', maxs)

row_vector2: [0 1 2 3 4 5]
Minimo: 0
Massimo: 5

matrix3:
 [[ 5  2  6]
 [ 8 12  1]]
Minimi delle righe: [2 1]
Massimi delle colonne: [ 8 12  6]


Se invece si desidera ottenere gli indici di tali elementi, è possibile utilizzare i metodi **.argmin(...)** e **.argmax(...)**.

In [30]:
# Indici posizionali dei minimi delle righe di una matrice
min_indices = matrix3.argmin(axis=1)
print('Indici dei minimi:\n', min_indices)

# Indici posizionali dei massimi delle colonne di una matrice
max_indices = matrix3.argmax(axis=0)
print('Indici dei massimi:\n', max_indices) 

Indici dei minimi:
 [1 2]
Indici dei massimi:
 [1 1 0]
